services:
  nginx:
    image: nginx:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/options-ssl-nginx.conf:/etc/nginx/conf.d/options-ssl-nginx.conf
      - ./data/ssl-dhparams.pem:/etc/nginx/conf.d/ssl-dhparams.pem
    ports:
      - "80:80"
      - "443:443"
    networks:
      - xendpal_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile  
    networks:
      - xendpal_network

networks:
  xendpal_network:
    driver: bridge
